### ISSUE TITLE
Pretty sweet! How do updates work? Is there a generator?

### ISSUE THREAD

**Issue by TKIPisalegacycipher** [DocNougat/Meraki-Powershell-Module#1]
Super dope! I'm wondering how you would update this when new API operations are released. I didn't see a "generator" script in the repo. Do you generate the operations programmatically?

In any case, great work! Wishing you much success here.

**Comment by DocNougat** [comment]
Thanks! No generator. Right now I'm handling updates from the API by just manually adding or removing a function as needed. In the six months I've been working on this in my spare time there haven't been many changes.
