### ISSUE TITLE
Custom user agent strings

### ISSUE THREAD

**Issue by TKIPisalegacycipher** [DocNougat/Meraki-Powershell-Module#2]
Are developers who consume the module able to [specify user agent strings as a best practice](https://developer.cisco.com/meraki/api-v1/user-agents-overview/)?

What does the module send in its user agent string by default?

**Comment by DocNougat** [comment]
This is a great idea and definitely an oversight on my part. I'll add it to the list of to-dos

**Comment by DocNougat** [comment]
The module has been updated to version 1.0.2 and will now send an identifying useragent string with every request.
